apiVersion: v1
kind: Service
metadata:
  name: planet-service-node-port
spec:
  type: NodePort
  ports:
    - port: 3050
      targetPort: 8080
      nodePort: 30080
  selector:
    component: planet-service